name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: forgejo.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_OP_CLIENT_ID: ${{ vars.VITE_OP_CLIENT_ID }}
          VITE_OP_API_URL: ${{ vars.VITE_OP_API_URL }}
          VITE_OP_REPLAY_SAMPLE_RATE: ${{ vars.VITE_OP_REPLAY_SAMPLE_RATE }}

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --dir=./dist/webpage --prod --no-build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}