name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: forgejo.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_OP_CLIENT_ID: ${{ vars.VITE_OP_CLIENT_ID }}
          VITE_OP_API_URL: ${{ vars.VITE_OP_API_URL }}
          VITE_OP_REPLAY_SAMPLE_RATE: ${{ vars.VITE_OP_REPLAY_SAMPLE_RATE }}
          VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
          VITE_SENTRY_TUNNEL: ${{ vars.VITE_SENTRY_TUNNEL }}
          VITE_SENTRY_ENVIRONMENT: ${{ vars.VITE_SENTRY_ENVIRONMENT }}
          VITE_SENTRY_TRACES_SAMPLE_RATE: ${{ vars.VITE_SENTRY_TRACES_SAMPLE_RATE }}

      - name: Install glitchtip-cli
        run: curl -fsSL https://glitchtip.com/install.sh | sh

      - name: Upload source maps
        run: |
          glitchtip-cli sourcemaps inject ./dist/webpage
          glitchtip-cli sourcemaps upload ./dist/webpage \
            --url "${{ vars.GLITCHTIP_URL }}" \
            --org "${{ vars.GLITCHTIP_ORG }}" \
            --project "${{ vars.GLITCHTIP_PROJECT }}" \
            --release "${{ vars.VER || github.sha }}"

        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.GLITCHTIP_API_TOKEN }}
        continue-on-error: true

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy ./dist/webpage --branch=main --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
